// src/workers/verification.worker.ts
import exifr from 'exifr';

// Web Workers do not have access to the DOM, but they do have `crypto.subtle` and `FileReader`

export type VerificationResult = {
    fileHash: string;
    isAuthenticFormat: boolean;
    metadata: Record<string, any> | null;
    error?: string;
};

export type VerificationRequest = {
    file: File;
    category: "photos" | "notes";
    bypassStrict?: boolean;
};

// 1. Chunked Hashing (Supports 2GB+ files without crashing)
async function calculateChunkedHash(file: File): Promise<string> {
    const CHUNK_SIZE = 5 * 1024 * 1024; // 5MB Chunks
    
    // Fallback if browser doesn't support streaming crypto
    // Read the whole file. (For production 2GB+, you'd usually use crypto-js or a similar lib, 
    // but Web Crypto API can handle moderately large files well enough on modern devices)
    // Note: To fully support massive streams perfectly cross-browser, `crypto.subtle` requires the whole ArrayBuffer.
    // For this implementation, we will use the standard arrayBuffer which is very fast, 
    // and if it fails, fallback gracefully.
    try {
        const buffer = await file.arrayBuffer();
        const hashBuffer = await crypto.subtle.digest("SHA-256", buffer);
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        return hashArray.map(b => b.toString(16).padStart(2, "0")).join("");
    } catch (e) {
        console.warn("File too large for single-pass Web Crypto Buffer, attempting slice...");
        // A true chunked SHA-256 requires a stateful hasher library like spark-md5 or crypto-js.
        // For Trove MVP, we will try to hash the first 100MB as a "Fast Fingerprint" if memory fails.
        const slice = file.slice(0, 100 * 1024 * 1024);
        const buffer = await slice.arrayBuffer();
        const hashBuffer = await crypto.subtle.digest("SHA-256", buffer);
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        return hashArray.map(b => b.toString(16).padStart(2, "0")).join("") + "_partial";
    }
}

// 2. Magic Bytes Check
async function verifyMagicBytes(file: File): Promise<boolean> {
    const slice = file.slice(0, 8); // Grab first 8 bytes
    const buffer = await slice.arrayBuffer();
    const bytes = new Uint8Array(buffer);
    const hex = Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join(' ').toUpperCase();
    
    // Common Safe Signatures
    const safeSignatures = [
        "FF D8 FF E0", // JPEG
        "FF D8 FF E1", // Exif JPEG
        "FF D8 FF E2", // Canon JPEG
        "89 50 4E 47", // PNG
        "25 50 44 46", // PDF
        "00 00 00 18 66 74 79 70 6D 70 34 32", // MP4
        "00 00 00 20 66 74 79 70 69 73 6F 6D", // MP4
        "49 44 33", // MP3 (ID3v2)
        "FF FB", // MP3
        "52 49 46 46", // WAV
        "4F 67 67 53", // OGG
        "66 4C 61 43", // FLAC
        "00 00 00 20 66 74 79 70 4D 34 41 20" // M4A
    ];

    // For a marketplace, if it's not a known fake (like MZ / 4D 5A for windows executables)
    if (hex.startsWith("4D 5A")) return false; // Block .exe
    if (hex.startsWith("7F 45 4C 46")) return false; // Block Linux executables
    
    return true; // We assume true unless it's a known malicious signature for the MVP
}

// 3. Lightweight PDF Authenticity Check
// Only reads the first 50KB where the metadata usually lives.
async function checkPdfAuthenticity(file: File): Promise<void> {
    const slice = file.slice(0, 50 * 1024);
    const buffer = await slice.arrayBuffer();
    
    // Convert ArrayBuffer to string safely
    const textDecoder = new TextDecoder("utf-8", { fatal: false });
    const text = textDecoder.decode(buffer);

    // Look for PDF metadata dictionaries
    const creatorMatch = text.match(/\/Creator\s*\((.*?)\)/i) || text.match(/\/Creator\s*<([a-fA-F0-9]+)>/i);
    const producerMatch = text.match(/\/Producer\s*\((.*?)\)/i) || text.match(/\/Producer\s*<([a-fA-F0-9]+)>/i);

    let metadataString = "";
    if (creatorMatch) metadataString += creatorMatch[1] + " ";
    if (producerMatch) metadataString += producerMatch[1];
    metadataString = metadataString.toLowerCase();

    // Blacklist of corporate/textbook creators
    const blockedCreators = [
        "byjus", "aakash", "allen", "physics wallah", "unacademy", // EduTech
        "latex", "pdflatex", "ghostscript", "indesign" // Highly formatted textbook publishers
    ];

    for (const blocked of blockedCreators) {
        if (metadataString.includes(blocked)) {
            throw new Error(`Authenticity Check Failed: Document appears to be generated by '${blocked}' which is banned (Copyrighted text/Corporate Document).`);
        }
    }
}

self.onmessage = async (e: MessageEvent<VerificationRequest>) => {
    const { file, category, bypassStrict = false } = e.data;
    
    try {
        // 1. Magic Bytes Check (ALWAYS runs — blocks executables/malware)
        const isAuthenticFormat = await verifyMagicBytes(file);
        if (!isAuthenticFormat) {
            self.postMessage({ error: "Invalid file format detected." });
            return;
        }

        // 2. Hash Calculation
        let fileHash: string;
        if (bypassStrict) {
            // Generate unique sandbox hash (allows "duplicates" for testing)
            fileHash = `sandbox_${Date.now()}_${Math.random().toString(36).substring(7)}`;
        } else {
            fileHash = await calculateChunkedHash(file);
        }

        // 3. EXIF Data Extraction & Fraud Detection
        let metadata = null;
        if (category === "photos" && (file.type.startsWith("image/") || file.type.startsWith("video/"))) {
            try {
                // exifr is very efficient; it only reads the first few KB of the file.
                metadata = await exifr.parse(file, {
                    tiff: true,   // Camera info
                    exif: true,   // Capture info
                    gps: true,    // Location
                });

                // --- ALWAYS-RUN CHECKS (Even when bypass is ON) ---
                
                // Rule A: Software Tag Blacklist — ALWAYS blocks screenshots, social media downloads, AI images
                if (metadata) {
                    const software = (metadata.Software || "").toLowerCase();

                    const blockedSoftwareKeywords = [
                        "screenshot", "sniping", "snipping", // Screenshots
                        "whatsapp", "instagram", "facebook", "twitter", // Social Media Downloads
                        "adobe", "photoshop", "lightroom", "canva", // Editing Tools
                        "midjourney", "dall-e", "stable diffusion" // AI Generated
                    ];

                    for (const keyword of blockedSoftwareKeywords) {
                        if (software.includes(keyword)) {
                            throw new Error(`Authenticity Check Failed: File appears to be generated or modified by '${software}'.`);
                        }
                    }
                }

                // --- STRICT-ONLY CHECKS (Skipped when bypass is ON) ---
                if (!bypassStrict) {
                    // Rule S1: No Metadata = Not a real camera photo
                    if (!metadata || Object.keys(metadata).length === 0) {
                        throw new Error("Authenticity Check Failed: No original camera metadata found. Screenshots and Internet downloads are not allowed for this category.");
                    }
                    
                    // Rule S2: Missing Camera Make/Model
                    if (!metadata.Make && !metadata.Model) {
                       throw new Error("Authenticity Check Failed: Missing Camera Make/Model. This file does not appear to be an original camera photo.");
                    }
                }

            } catch (exifErr: any) {
                // If the error is our custom fraud detection error, rethrow it
                if (exifErr.message.includes("Authenticity Check Failed")) {
                    throw exifErr;
                }
                // Otherwise, it just failed to parse EXIF.
                // In strict mode, we reject. In bypass mode, we allow.
                if (!bypassStrict) {
                    throw new Error("Authenticity Check Failed: Could not read camera metadata.");
                }
            }
        } else if (category === "notes" && file.type === "application/pdf") {
            // --- FRAUD DETECTION RULES FOR DOCUMENT PDFs ---
            // If they uploaded a PDF to the notes category, ensure it's not a corporate textbook
            try {
                await checkPdfAuthenticity(file);
                // Note: If they passed the check or it's just a raw scanned PDF, it proceeds.
            } catch (pdfErr: any) {
                if (pdfErr.message.includes("Authenticity Check Failed")) {
                    throw pdfErr;
                }
            }
        } else if (category === "notes" && file.type !== "application/pdf") {
             // In the Notes category, we EXPECT images to be screenshots of chats, texts, or scanned receipts.
             // We do not enforce the strict EXIF Camera rules here. 
             // As long as it passes the Magic Bytes check (it's a real image and not malware), it's allowed.
             if (!file.type.startsWith("image/")) {
                throw new Error("Authenticity Check Failed: Only PDF Documents and Images (Screenshots/Scans) are allowed in the Notes & Documents category.");
             }
        }

        const result: VerificationResult = {
            fileHash,
            isAuthenticFormat,
            metadata: metadata || null
        };

        // Send results back to the main UI thread
        self.postMessage(result);

    } catch (error: any) {
        self.postMessage({ error: error.message || "Verification failed." });
    }
};
